name: Setup
description: Sets up project for CI jobs
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        cache: yarn
        node-version: 16
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: sh
